<dg:assign name="cdrRecordType"  set= \>
<dg:assign name="globalCallID_callManagerId"  set= \>
<dg:assign name="globalCallID_callId"  set= \>
<dg:assign name="origLegCallIdentifier"  set= \>
<dg:assign name="dateTimeOrigination"  set= \>
<dg:assign name="origNodeId"  set= \>
<dg:assign name="origSpan"  set= \>
<dg:assign name="origIpAddr"  set= \>
<dg:assign name="callingPartyNumber"  set= \>
<dg:assign name="callingPartyUnicodeLoginUserID"  set= \>
<dg:assign name="origCause_location"  set= \>
<dg:assign name="origCause_value"  set= \>
<dg:assign name="origPrecedenceLevel"  set= \>
<dg:assign name="origMediaTransportAddress_IP"  set= \>
<dg:assign name="origMediaTransportAddress_Port"  set= \>
<dg:assign name="origMediaCap_payloadCapability"  set= \>
<dg:assign name="origMediaCap_maxFramesPerPacket"  set= \>
<dg:assign name="origVideoCap_Codec"  set= \>
<dg:assign name="origVideoCap_Bandwidth"  set= \>
<dg:assign name="origVideoCap_Resolution"  set= \>
<dg:assign name="origVideoTransportAddress_IP"  set= \>
<dg:assign name="origVideoTransportAddress_Port"  set= \>
<dg:assign name="origRSVPAudioStat"  set= \>
<dg:assign name="origRSVPVideoStat"  set= \>
<dg:assign name="destLegCallIdentifier"  set= \>
<dg:assign name="destNodeId"  set= \>
<dg:assign name="destSpan"  set= \>
<dg:assign name="destIpAddr"  set= \>
<dg:assign name="originalCalledPartyNumber"  set= \>
<dg:assign name="finalCalledPartyNumber"  set= \>
<dg:assign name="finalCalledPartyUnicodeLoginUserID"  set= \>
<dg:assign name="destCause_location"  set= \>
<dg:assign name="destCause_value"  set= \>
<dg:assign name="destPrecedenceLevel"  set= \>
<dg:assign name="destMediaTransportAddress_IP"  set= \>
<dg:assign name="destMediaTransportAddress_Port"  set= \>
<dg:assign name="destMediaCap_payloadCapability"  set= \>
<dg:assign name="destMediaCap_maxFramesPerPacket"  set= \>
<dg:assign name="destVideoCap_Codec"  set= \>
<dg:assign name="destVideoCap_Bandwidth"  set= \>
<dg:assign name="destVideoCap_Resolution"  set= \>
<dg:assign name="destVideoTransportAddress_IP"  set= \>
<dg:assign name="destVideoTransportAddress_Port"  set= \>
<dg:assign name="destRSVPAudioStat"  set= \>
<dg:assign name="destRSVPVideoStat"  set= \>
<dg:assign name="dateTimeConnect"  set= \>
<dg:assign name="dateTimeDisconnect"  set= \>
<dg:assign name="lastRedirectDn"  set= \>
<dg:assign name="pkid"  set= \>
<dg:assign name="originalCalledPartyNumberPartition"  set= \>
<dg:assign name="NumberPartition"  set= \>
<dg:assign name="finalCalledPartyNumberPartition"  set= \>
<dg:assign name="lastRedirectDnPartition"  set= \>
<dg:assign name="duration"  set= \>
<dg:assign name="origDeviceName"  set= \>
<dg:assign name="destDeviceName"  set= \>
<dg:assign name="origCallTerminationOnBehalfOf"  set= \>
<dg:assign name="destCallTerminationOnBehalfOf"  set= \>
<dg:assign name="origCalledPartyRedirectOnBehalfOf"  set= \>
<dg:assign name="lastRedirectRedirectOnBehalfOf"  set= \>
<dg:assign name="origCalledPartyRedirectReason"  set= \>
<dg:assign name="lastRedirectRedirectReason"  set= \>
<dg:assign name="destConversationID"  set= \>
<dg:assign name="globalCallId_ClusterId"  set= \>
<dg:assign name="joinOnBehalfOf"  set= \>
<dg:assign name="comment"  set= \>
<dg:assign name="authCodeDescription"  set= \>
<dg:assign name="authorizationLevel"  set= \>
<dg:assign name="clientMatterCode"  set= \>
<dg:assign name="origDTMFMethod"  set= \>
<dg:assign name="destDTMFMethod"  set= \>
<dg:assign name="callSecuredStatus"  set= \>
<dg:assign name="origConversationID"  set= \>
<dg:assign name="origMediaCap_Bandwidth"  set= \>
<dg:assign name="destMediaCap_Bandwidth"  set= \>
<dg:assign name="authorizationCodeValue"  set= \>
<dg:assign name="outpulsedCallingPartyNumber"  set= \>
<dg:assign name="outpulsedCalledPartyNumber"  set= \>
<dg:assign name="origIpv4v6Addr"  set= \>
<dg:assign name="destIpv4v6Addr"  set= \>
<dg:assign name="origVideoCap_Codec_Channel2"  set= \>
<dg:assign name="origVideoCap_Bandwidth_Channel2"  set= \>
<dg:assign name="origVideoCap_Resolution_Channel2"  set= \>
<dg:assign name="origVideoTransportAddress_IP_Channel2"  set= \>
<dg:assign name="origVideoTransportAddress_Port_Channel2"  set= \>
<dg:assign name="origVideoChannel_Role_Channel2"  set= \>
<dg:assign name="destVideoCap_Codec_Channel2"  set= \>
<dg:assign name="destVideoCap_Bandwidth_Channel2"  set= \>
<dg:assign name="destVideoCap_Resolution_Channel2"  set= \>
<dg:assign name="destVideoTransportAddress_IP_Channel2"  set= \>
<dg:assign name="destVideoTransportAddress_Port_Channel2"  set= \>
<dg:assign name="destVideoChannel_Role_Channel2"  set= \>
<dg:assign name="IncomingProtocolID"  set= \>
<dg:assign name="IncomingProtocolCallRef"  set= \>
<dg:assign name="OutgoingProtocolID"  set= \>
<dg:assign name="OutgoingProtocolCallRef"  set= \>
<dg:assign name="currentRoutingReason"  set= \>
<dg:assign name="origRoutingReason"  set= \>
<dg:assign name="lastRedirectingRoutingReason"  set= \>
<dg:assign name="huntPilotDN"  set= \>
<dg:assign name="huntPilotPartition" set= \>
<dg:assign name= set= \>
