<state id="A1"><onentry><dg:assign name="cdrRecordType"  from="0" to="100" step="1"/><\/onentry><transition target="A2" event="A2"\/><\/state>
<state id="A2"><onentry><dg:assign name="globalCallID_callManagerId"  set="#{random_integer}"/><\/onentry><transition target="A3" event="A3"\/><\/state>
<state id="A3"><onentry><dg:assign name="globalCallID_callId"  set="#{random_integer}"/><\/onentry><transition target="A4" event="A4"\/><\/state>
<state id="A4"><onentry><dg:assign name="origLegCallIdentifier"  set="#{random_integer}"/><\/onentry><transition target="A5" event="A5"\/><\/state>
<state id="A5"><onentry><dg:assign name="dateTimeOrigination"  set="#{random_integer}"/><\/onentry><transition target="A6" event="A6"\/><\/state>
<state id="A6"><onentry><dg:assign name="origNodeId"  set="#{random_integer}"/><\/onentry><transition target="A7" event="A7"\/><\/state>
<state id="A7"><onentry><dg:assign name="origSpan"  set="#{random_integer}"/><\/onentry><transition target="A8" event="A8"\/><\/state>
<state id="A8"><onentry><dg:assign name="origIpAddr"  set="#{random_integer}"/><\/onentry><transition target="A9" event="A9"\/><\/state>
<state id="A9"><onentry><dg:assign name="callingPartyNumber"  set="#{random_text}"/><\/onentry><transition target="A10" event="A10"\/><\/state>
<state id="A10"><onentry><dg:assign name="callingPartyUnicodeLoginUserID"  set="#{random_text}"/><\/onentry><transition target="A11" event="A11"\/><\/state>
<state id="A11"><onentry><dg:assign name="origCause_location" set="#{random_decimal}"/><\/onentry><transition target="A12" event="A12"\/><\/state>
<state id="A12"><onentry><dg:assign name="origCause_value"  set="#{random_decimal}"/><\/onentry><transition target="A13" event="A13"\/><\/state>
<state id="A13"><onentry><dg:assign name="origPrecedenceLevel"  set="#{random_decimal}"/><\/onentry><transition target="A14" event="A14"\/><\/state>
<state id="A14"><onentry><dg:assign name="origMediaTransportAddress_IP"  set="#{random_integer}"/><\/onentry><transition target="A15" event="A15"\/><\/state>
<state id="A15"><onentry><dg:assign name="origMediaTransportAddress_Port"  set="#{random_integer}"/><\/onentry><transition target="A16" event="A16"\/><\/state>
<state id="A16"><onentry><dg:assign name="origMediaCap_payloadCapability"  set="#{random_integer}"/><\/onentry><transition target="A17" event="A17"\/><\/state>
<state id="A17"><onentry><dg:assign name="origMediaCap_maxFramesPerPacket"  set="#{random_integer}"/><\/onentry><transition target="A18" event="A18"\/><\/state>
<state id="A18"><onentry><dg:assign name="origVideoCap_Codec"  set="#{random_decimal}"/><\/onentry><transition target="A19" event="A19"\/><\/state>
<state id="A19"><onentry><dg:assign name="origVideoCap_Bandwidth"  set="#{random_integer}"/><\/onentry><transition target="A20" event="A20"\/><\/state>
<state id="A20"><onentry><dg:assign name="origVideoCap_Resolution"  set="#{random_decimal}"/><\/onentry><transition target="A21" event="A21"\/><\/state>
<state id="A21"><onentry><dg:assign name="origVideoTransportAddress_IP"  set="#{random_integer}"/><\/onentry><transition target="A22" event="A22"\/><\/state>
<state id="A22"><onentry><dg:assign name="origVideoTransportAddress_Port"  set="#{random_integer}"/><\/onentry><transition target="A23" event="A23"\/><\/state>
<state id="A23"><onentry><dg:assign name="origRSVPAudioStat"  set="#{random_decimal}"/><\/onentry><transition target="A24" event="A24"\/><\/state>
<state id="A24"><onentry><dg:assign name="origRSVPVideoStat"  set="#{random_decimal}"/><\/onentry><transition target="A25" event="A25"\/><\/state>
<state id="A25"><onentry><dg:assign name="destLegCallIdentifier"  set="#{random_integer}"/><\/onentry><transition target="A26" event="A26"\/><\/state>
<state id="A26"><onentry><dg:assign name="destNodeId"  set="#{random_integer}"/><\/onentry><transition target="A27" event="A27"\/><\/state>
<state id="A27"><onentry><dg:assign name="destSpan"  set="#{random_integer}"/><\/onentry><transition target="A28" event="A28"\/><\/state>
<state id="A28"><onentry><dg:assign name="destIpAddr"  set="#{random_integer}"/><\/onentry><transition target="A29" event="A29"\/><\/state>
<state id="A29"><onentry><dg:assign name="originalCalledPartyNumber"  set="#{random_text}"/><\/onentry><transition target="A30" event="A30"\/><\/state>
<state id="A30"><onentry><dg:assign name="finalCalledPartyNumber"  set="#{random_text}"/><\/onentry><transition target="A31" event="A31"\/><\/state>
<state id="A31"><onentry><dg:assign name="finalCalledPartyUnicodeLoginUserID"  set="#{random_text}"/><\/onentry><transition target="A32" event="A32"\/><\/state>
<state id="A32"><onentry><dg:assign name="destCause_location"  set="#{random_decimal}"/><\/onentry><transition target="A33" event="A33"\/><\/state>
<state id="A33"><onentry><dg:assign name="destCause_value"  set="#{random_decimal}"/><\/onentry><transition target="A34" event="A34"\/><\/state>
<state id="A34"><onentry><dg:assign name="destPrecedenceLevel"  set="#{random_decimal}"/><\/onentry><transition target="A35" event="A35"\/><\/state>
<state id="A35"><onentry><dg:assign name="destMediaTransportAddress_IP"  set="#{random_integer}"/><\/onentry><transition target="A36" event="A36"\/><\/state>
<state id="A36"><onentry><dg:assign name="destMediaTransportAddress_Port"  set="#{random_integer}"/><\/onentry><transition target="A37" event="A37"\/><\/state>
<state id="A37"><onentry><dg:assign name="destMediaCap_payloadCapability"  set="#{random_integer}"/><\/onentry><transition target="A38" event="A38"\/><\/state>
<state id="A38"><onentry><dg:assign name="destMediaCap_maxFramesPerPacket"  set="#{random_integer}"/><\/onentry><transition target="A39" event="A39"\/><\/state>
<state id="A39"><onentry><dg:assign name="destVideoCap_Codec"  set="#{random_decimal}"/><\/onentry><transition target="A40" event="A40"\/><\/state>
<state id="A40"><onentry><dg:assign name="destVideoCap_Bandwidth"  set="#{random_integer}"/><\/onentry><transition target="A41" event="A41"\/><\/state>
<state id="A41"><onentry><dg:assign name="destVideoCap_Resolution"  set="#{random_decimal}"/><\/onentry><transition target="A42" event="A42"\/><\/state>
<state id="A42"><onentry><dg:assign name="destVideoTransportAddress_IP"  set="#{random_integer}"/><\/onentry><transition target="A43" event="A43"\/><\/state>
<state id="A43"><onentry><dg:assign name="destVideoTransportAddress_Port"  set="#{random_integer}"/><\/onentry><transition target="A44" event="A44"\/><\/state>
<state id="A44"><onentry><dg:assign name="destRSVPAudioStat"  set="#{random_decimal}"/><\/onentry><transition target="A45" event="A45"\/><\/state>
<state id="A45"><onentry><dg:assign name="destRSVPVideoStat"  set="#{random_decimal}"/><\/onentry><transition target="A46" event="A46"\/><\/state>
<state id="A46"><onentry><dg:assign name="dateTimeConnect"  set="#{random_integer}"/><\/onentry><transition target="A47" event="A47"\/><\/state>
<state id="A47"><onentry><dg:assign name="dateTimeDisconnect"  set="#{random_integer}"/><\/onentry><transition target="A48" event="A48"\/><\/state>
<state id="A48"><onentry><dg:assign name="lastRedirectDn"  set="#{random_text}"/><\/onentry><transition target="A49" event="A49"\/><\/state>
<state id="A49"><onentry><dg:assign name="pkid"  set="#{random_text}"/><\/onentry><transition target="A50" event="A50"\/><\/state>
<state id="A50"><onentry><dg:assign name="originalCalledPartyNumberPartition"  set="#{random_text}"/><\/onentry><transition target="A51" event="A51"\/><\/state>
<state id="A51"><onentry><dg:assign name="NumberPartition"  set="#{random_text}"/><\/onentry><transition target="A52" event="A52"\/><\/state>
<state id="A52"><onentry><dg:assign name="finalCalledPartyNumberPartition"  set="#{random_text}"/><\/onentry><transition target="A53" event="A53"\/><\/state>
<state id="A53"><onentry><dg:assign name="lastRedirectDnPartition"  set="#{random_text}"/><\/onentry><transition target="A54" event="A54"\/><\/state>
<state id="A54"><onentry><dg:assign name="duration"  set="#{random_integer}"/><\/onentry><transition target="A55" event="A55"\/><\/state>
<state id="A55"><onentry><dg:assign name="origDeviceName"  set="#{random_text}"/><\/onentry><transition target="A56" event="A56"\/><\/state>
<state id="A56"><onentry><dg:assign name="destDeviceName"  set="#{random_text}"/><\/onentry><transition target="A57" event="A57"\/><\/state>
<state id="A57"><onentry><dg:assign name="origCallTerminationOnBehalfOf"  set="#{random_integer}"/><\/onentry><transition target="A58" event="A58"\/><\/state>
<state id="A58"><onentry><dg:assign name="destCallTerminationOnBehalfOf"  set="#{random_integer}"/><\/onentry><transition target="A59" event="A59"\/><\/state>
<state id="A59"><onentry><dg:assign name="origCalledPartyRedirectOnBehalfOf"  set="#{random_integer}"/><\/onentry><transition target="A60" event="A60"\/><\/state>
<state id="A60"><onentry><dg:assign name="lastRedirectRedirectOnBehalfOf"  set="#{random_integer}"/><\/onentry><transition target="A61" event="A61"\/><\/state>
<state id="A61"><onentry><dg:assign name="origCalledPartyRedirectReason"  set="#{random_integer}"/><\/onentry><transition target="A62" event="A62"\/><\/state>
<state id="A62"><onentry><dg:assign name="lastRedirectRedirectReason"  set="#{random_integer}"/><\/onentry><transition target="A63" event="A63"\/><\/state>
<state id="A63"><onentry><dg:assign name="destConversationID"  set="#{random_integer}"/><\/onentry><transition target="A64" event="A64"\/><\/state>
<state id="A64"><onentry><dg:assign name="globalCallId_ClusterId"  set="#{random_text}"/><\/onentry><transition target="A65" event="A65"\/><\/state>
<state id="A65"><onentry><dg:assign name="joinOnBehalfOf"   set="#{random_integer}"/><\/onentry><transition target="A66" event="A66"\/><\/state>
<state id="A66"><onentry><dg:assign name="comment"  set="#{random_text}"/><\/onentry><transition target="A67" event="A67"\/><\/state>
<state id="A67"><onentry><dg:assign name="authCodeDescription"  set="#{random_text}"/><\/onentry><transition target="A68" event="A68"\/><\/state>
<state id="A68"><onentry><dg:assign name="authorizationLevel"  set="#{random_integer}"/><\/onentry><transition target="A69" event="A69"\/><\/state>
<state id="A69"><onentry><dg:assign name="clientMatterCode"  set="#{random_text}"/><\/onentry><transition target="A70" event="A70"\/><\/state>
<state id="A70"><onentry><dg:assign name="origDTMFMethod"  set="#{random_integer}"/><\/onentry><transition target="A71" event="A71"\/><\/state>
<state id="A71"><onentry><dg:assign name="destDTMFMethod"  set="#{random_integer}"/><\/onentry><transition target="A72" event="A72"\/><\/state>
<state id="A72"><onentry><dg:assign name="callSecuredStatus"  set="#{random_integer}"/><\/onentry><transition target="A73" event="A73"\/><\/state>
<state id="A73"><onentry><dg:assign name="origConversationID"  set="#{random_integer}"/><\/onentry><transition target="A74" event="A74"\/><\/state>
<state id="A74"><onentry><dg:assign name="origMediaCap_Bandwidth"  set="#{random_integer}"/><\/onentry><transition target="A75" event="A75"\/><\/state>
<state id="A75"><onentry><dg:assign name="destMediaCap_Bandwidth"  set="#{random_integer}"/><\/onentry><transition target="A76" event="A76"\/><\/state>
<state id="A76"><onentry><dg:assign name="authorizationCodeValue"  set="#{random_text}"/><\/onentry><transition target="A77" event="A77"\/><\/state>
<state id="A77"><onentry><dg:assign name="outpulsedCallingPartyNumber"  set="#{random_text}"/><\/onentry><transition target="A78" event="A78"\/><\/state>
<state id="A78"><onentry><dg:assign name="outpulsedCalledPartyNumber"  set="#{random_text}"/><\/onentry><transition target="A79" event="A79"\/><\/state>
<state id="A79"><onentry><dg:assign name="origIpv4v6Addr"  set="#{random_text}"/><\/onentry><transition target="A80" event="A80"\/><\/state>
<state id="A80"><onentry><dg:assign name="destIpv4v6Addr"  set="#{random_text}"/><\/onentry><transition target="A81" event="A81"\/><\/state>
<state id="A81"><onentry><dg:assign name="origVideoCap_Codec_Channel2"  set="#{random_decimal}"/><\/onentry><transition target="A82" event="A82"\/><\/state>
<state id="A82"><onentry><dg:assign name="origVideoCap_Bandwidth_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A83" event="A83"\/><\/state>
<state id="A83"><onentry><dg:assign name="origVideoCap_Resolution_Channel2"  set="#{random_decimal}"/><\/onentry><transition target="A84" event="A84"\/><\/state>
<state id="A84"><onentry><dg:assign name="origVideoTransportAddress_IP_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A85" event="A85"\/><\/state>
<state id="A85"><onentry><dg:assign name="origVideoTransportAddress_Port_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A86" event="A86"\/><\/state>
<state id="A86"><onentry><dg:assign name="origVideoChannel_Role_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A87" event="A87"\/><\/state>
<state id="A87"><onentry><dg:assign name="destVideoCap_Codec_Channel2"  set="#{random_decimal}"/><\/onentry><transition target="A88" event="A88"\/><\/state>
<state id="A88"><onentry><dg:assign name="destVideoCap_Bandwidth_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A89" event="A89"\/><\/state>
<state id="A89"><onentry><dg:assign name="destVideoCap_Resolution_Channel2"  set="#{random_decimal}"/><\/onentry><transition target="A90" event="A90"\/><\/state>
<state id="A90"><onentry><dg:assign name="destVideoTransportAddress_IP_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A91" event="A91"\/><\/state>
<state id="A91"><onentry><dg:assign name="destVideoTransportAddress_Port_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A92" event="A92"\/><\/state>
<state id="A92"><onentry><dg:assign name="destVideoChannel_Role_Channel2"  set="#{random_integer}"/><\/onentry><transition target="A93" event="A93"\/><\/state>
<state id="A93"><onentry><dg:assign name="IncomingProtocolID"  set="#{random_integer}"/><\/onentry><transition target="A94" event="A94"\/><\/state>
<state id="A94"><onentry><dg:assign name="IncomingProtocolCallRef"  set="#{random_text}"/><\/onentry><transition target="A95" event="A95"\/><\/state>
<state id="A95"><onentry><dg:assign name="OutgoingProtocolID"  set="#{random_integer}"/><\/onentry><transition target="A96" event="A96"\/><\/state>
<state id="A96"><onentry><dg:assign name="OutgoingProtocolCallRef"  set="#{random_text}"/><\/onentry><transition target="A97" event="A97"\/><\/state>
<state id="A97"><onentry><dg:assign name="currentRoutingReason"  set="#{random_integer}"/><\/onentry><transition target="A98" event="A98"\/><\/state>
<state id="A98"><onentry><dg:assign name="origRoutingReason"  set="#{random_integer}"/><\/onentry><transition target="A99" event="A99"\/><\/state>
<state id="A99"><onentry><dg:assign name="lastRedirectingRoutingReason"  set="#{random_integer}"/><\/onentry><transition target="A100" event="A100"\/><\/state>
<state id="A100"><onentry><dg:assign name="huntPilotDN"  set="#{random_text}"/><\/onentry><transition target="A101" event="A101"\/><\/state>
<state id="A101"><onentry><dg:assign name="huntPilotPartition"  set="#{random_text}"/><\/onentry><transition target="A102" event="A102"\/><\/state>
